export const STORE_EDIT_HANDLER = 'STORE_EDIT_HANDLER'
export const STORE_RECTANGLE_LAYER = 'STORE_RECTANGLE_LAYER'
export const FILTER_DRAW_TOGGLE = 'FILTER_DRAW_TOGGLE'
export const SET_DRAW_TRIGGER_SOURCE = 'SET_DRAW_TRIGGER_SOURCE'
