# Generated by Django 3.1.7 on 2021-03-17 04:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeologicalProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ptype', models.CharField(blank=True, max_length=70, null=True)),
                ('rank', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HolderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HolderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OccName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='OccOriginalID',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OccSize',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OccStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OccStatusSimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OccType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OccTypeSimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('ind', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4202)),
                ('geoprovince', models.ManyToManyField(blank=True, related_name='geoprovince_occurrence', to='gp.GeologicalProvince')),
                ('govregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='govregion_occurrence', to='gp.governmentregion')),
                ('localgov', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localgov_occurrence', to='gp.localgovernment')),
                ('majmat', models.ManyToManyField(blank=True, related_name='majmat_occurrence', to='gp.Material')),
                ('minmat', models.ManyToManyField(blank=True, related_name='minmat_occurrence', to='gp.Material')),
                ('name', models.ManyToManyField(blank=True, related_name='name_occurrence', to='gp.OccName')),
                ('oid', models.ManyToManyField(blank=True, related_name='oid_occurrence', to='gp.OccOriginalID')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_occurrence', to='gp.occsize')),
            ],
        ),
        migrations.CreateModel(
            name='Shore',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TenAct',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('state', models.CharField(max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenement',
            fields=[
                ('ind', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('lodgedate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4202)),
                ('geoprovince', models.ManyToManyField(blank=True, related_name='geoprovince_tenement', to='gp.GeologicalProvince')),
                ('govregion', models.ManyToManyField(blank=True, related_name='govregion_tenement', to='gp.GovernmentRegion')),
            ],
        ),
        migrations.CreateModel(
            name='TenOriginalID',
            fields=[
                ('code', models.CharField(max_length=22, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TenStatusSimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TenTypeSimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=70)),
                ('original', models.CharField(max_length=50)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='act_tentype', to='gp.tenact')),
                ('simple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_tentype', to='gp.tentypesimp')),
            ],
        ),
        migrations.CreateModel(
            name='TenStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=100)),
                ('simple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_tenstatus', to='gp.tenstatussimp')),
            ],
        ),
        migrations.CreateModel(
            name='TenHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percown', models.FloatField()),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_tenholder', to='gp.holder')),
                ('tenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenement_tenholder', to='gp.tenement')),
            ],
        ),
        migrations.CreateModel(
            name='TenementRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_inactive', to='gp.tenement')),
            ],
        ),
        migrations.CreateModel(
            name='TenementChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=6)),
                ('field', models.CharField(max_length=30)),
                ('lodgedateval', models.DateField(blank=True, null=True)),
                ('startdateval', models.DateField(blank=True, null=True)),
                ('enddateval', models.DateField(blank=True, null=True)),
                ('date', models.DateField()),
                ('holderval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holderval_tenement', to='gp.tenholder')),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_change', to='gp.tenement')),
                ('majmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majmatval_tenement', to='gp.material')),
                ('minmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minmatval_tenement', to='gp.material')),
                ('oidval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidval_tenement', to='gp.tenoriginalid')),
                ('statusval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statusval_tenement', to='gp.tenstatus')),
                ('typeval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeval_tenement', to='gp.tentype')),
            ],
        ),
        migrations.CreateModel(
            name='TenementAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_addition', to='gp.tenement')),
            ],
        ),
        migrations.AddField(
            model_name='tenement',
            name='holder',
            field=models.ManyToManyField(blank=True, related_name='holder_tenement', through='gp.TenHolder', to='gp.Holder'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='localgov',
            field=models.ManyToManyField(blank=True, related_name='localgov_tenement', to='gp.LocalGovernment'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='majmat',
            field=models.ManyToManyField(blank=True, related_name='majmat_tenement', to='gp.Material'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='minmat',
            field=models.ManyToManyField(blank=True, related_name='minmat_tenement', to='gp.Material'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='occurrence',
            field=models.ManyToManyField(blank=True, related_name='occurrence_tenement', to='gp.Occurrence'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='oid',
            field=models.ManyToManyField(blank=True, related_name='oid_tenement', to='gp.TenOriginalID'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='shore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shore_tenement', to='gp.shore'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_tenement', to='gp.state'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_tenement', to='gp.tenstatus'),
        ),
        migrations.AddField(
            model_name='tenement',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typ_tenement', to='gp.tentype'),
        ),
        migrations.CreateModel(
            name='OccurrenceRemoval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_inactive', to='gp.occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=6)),
                ('field', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_change', to='gp.occurrence')),
                ('majmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majmatval_occurrence', to='gp.material')),
                ('minmatval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minmatval_occurrence', to='gp.material')),
                ('nameval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holderval_occurrence', to='gp.occname')),
                ('oidval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oidval_occurrence', to='gp.occoriginalid')),
                ('statusval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statusval_occurrence', to='gp.occstatus')),
                ('typeval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typeval_occurrence', to='gp.occtype')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_addition', to='gp.occurrence')),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_occurrence', to='gp.state'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_occurrence', to='gp.occstatus'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='typ',
            field=models.ManyToManyField(blank=True, related_name='typ_occurrence', to='gp.OccType'),
        ),
        migrations.AddField(
            model_name='occtype',
            name='simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_occtype', to='gp.occtypesimp'),
        ),
        migrations.AddField(
            model_name='occstatus',
            name='simple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_occstatus', to='gp.occstatussimp'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='category_material', to='gp.MaterialCategory'),
        ),
        migrations.CreateModel(
            name='Listed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_listed', to='gp.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='holder',
            name='listed',
            field=models.ManyToManyField(blank=True, related_name='listed_holder', to='gp.Listed'),
        ),
        migrations.AddField(
            model_name='holder',
            name='typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typ_holder', to='gp.holdertype'),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percown', models.FloatField()),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_holderrelation', to='gp.holder')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name_holderrelation', to='gp.holder')),
            ],
            options={
                'unique_together': {('name', 'child')},
            },
        ),
    ]
