# Generated by Django 3.1.2 on 2021-08-14 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeologicalProvinceSpatial',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ptype', models.CharField(blank=True, max_length=70, null=True)),
                ('rank', models.CharField(blank=True, max_length=70, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4202)),
            ],
        ),
        migrations.CreateModel(
            name='GovernmentRegionSpatial',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4202)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovernmentSpatial',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4202)),
            ],
        ),
        migrations.CreateModel(
            name='StateSpatial',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4202)),
            ],
        ),
    ]
