# Generated by Django 3.1.2 on 2021-08-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('open_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
