# Generated by Django 3.1.7 on 2021-03-17 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenholder',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_tenholder', to='gp.holderposition'),
        ),
    ]
