# Generated by Django 3.1.2 on 2021-08-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_geologicalprovincespatial_governmentregionspatial_localgovernmentspatial_statespatial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geologicalprovince',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='governmentregion',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='localgovernment',
            name='geom',
        ),
        migrations.RemoveField(
            model_name='state',
            name='geom',
        ),
    ]
