# Generated by Django 3.1.2 on 2021-08-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_userlogon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogon',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
