# Generated by Django 3.1.7 on 2021-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20210317_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
