# Generated by Django 3.1.2 on 2021-12-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_auto_20211130_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='user_edit',
            field=models.BooleanField(default=True),
        ),
    ]
