# Generated by Django 3.1.7 on 2021-03-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_auto_20210318_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenholder',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='name_tenholder', to='gp.holder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenholder',
            name='tenement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tenement_tenholder', to='gp.tenement'),
            preserve_default=False,
        ),
    ]
