# Generated by Django 3.1.2 on 2021-12-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_auto_20211215_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('issue', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_issue', to='gp.tenement')),
            ],
        ),
        migrations.CreateModel(
            name='OccIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('issue', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_issue', to='gp.occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='OccDeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('reviewed', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_occdeleterequest', to='gp.occurrence')),
            ],
        ),
    ]
