# Generated by Django 3.1.7 on 2021-03-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_auto_20210323_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listed',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenholder',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
