# Generated by Django 3.1.2 on 2021-12-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_occdeleterequest_occissue_tenissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenissue',
            name='ind',
        ),
        migrations.RenameField(
            model_name='occdeleterequest',
            old_name='reason',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='occdeleterequest',
            name='ind',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='OccIssue',
        ),
        migrations.DeleteModel(
            name='TenIssue',
        ),
    ]
