# Generated by Django 3.1.2 on 2021-12-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_auto_20211217_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='occdeleterequest',
            name='reviewed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
