# Generated by Django 3.1.2 on 2021-12-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0006_auto_20211230_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
