# Generated by Django 3.1.7 on 2021-04-12 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0007_auto_20210412_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='modified',
        ),
    ]
