# Generated by Django 3.1.7 on 2021-04-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0008_remove_holder_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='user_input',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='holder',
            name='valid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
