# Generated by Django 3.1.7 on 2021-04-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0009_auto_20210412_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
