# Generated by Django 3.1.7 on 2021-04-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0010_holder_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='holder',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listed',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='listed',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occname',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occname',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occoriginalid',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occoriginalid',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenement',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenement',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenholder',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenholder',
            name='valid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenoriginalid',
            name='user_input',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tenoriginalid',
            name='valid',
            field=models.BooleanField(),
        ),
    ]
