# Generated by Django 3.1.7 on 2021-04-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0011_auto_20210412_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='listed',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='occname',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='occoriginalid',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenement',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenoriginalid',
            name='modified',
        ),
    ]
