# Generated by Django 3.1.7 on 2021-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0012_auto_20210412_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='valid',
        ),
        migrations.AddField(
            model_name='holder',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listed',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occname',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occoriginalid',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenement',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenholder',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenoriginalid',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
