# Generated by Django 3.1.7 on 2021-04-14 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0015_auto_20210412_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listed',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='listed',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occname',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='occname',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occoriginalid',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='occoriginalid',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='tenoriginalid',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenoriginalid',
            name='user_input',
        ),
        migrations.AddField(
            model_name='holder',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listed',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occname',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occoriginalid',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenoriginalid',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holder',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listed',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occname',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='occoriginalid',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenoriginalid',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
