# Generated by Django 3.1.7 on 2021-04-16 06:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0016_auto_20210414_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listed',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occname',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occname',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occoriginalid',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='occoriginalid',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenement',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenholder',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenholder',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenholder',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenholder',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenoriginalid',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tenoriginalid',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='holder',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenement',
            name='user_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenement',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
