# Generated by Django 3.1.7 on 2021-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0017_auto_20210416_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='listed',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occname',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occoriginalid',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='tenement',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='user_input',
        ),
        migrations.RemoveField(
            model_name='tenoriginalid',
            name='user_input',
        ),
        migrations.AddField(
            model_name='holder',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listed',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occname',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occoriginalid',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenement',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenholder',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenoriginalid',
            name='user',
            field=models.CharField(default='tpm990ss', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HolderPosition',
        ),
    ]
