# Generated by Django 3.1.7 on 2021-04-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0018_auto_20210420_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listed',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='tenholder',
            old_name='id',
            new_name='_id',
        ),
        migrations.RemoveField(
            model_name='geologicalprovince',
            name='id',
        ),
        migrations.RemoveField(
            model_name='governmentregion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='holder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='holdertype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='localgovernment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='materialcategory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='occname',
            name='id',
        ),
        migrations.RemoveField(
            model_name='occstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='occstatussimp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='occtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='occtypesimp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tenstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tenstatussimp',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tentype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tentypesimp',
            name='id',
        ),
        migrations.AddField(
            model_name='geologicalprovince',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governmentregion',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holder',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holdertype',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localgovernment',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialcategory',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occname',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occstatus',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occstatussimp',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occtype',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occtypesimp',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstatus',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenstatussimp',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentype',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tentypesimp',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
