# Generated by Django 3.1.7 on 2021-04-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0019_auto_20210421_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='created',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenholder',
            name='valid',
        ),
    ]
