# Generated by Django 3.1.7 on 2021-04-25 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0021_auto_20210422_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencechange',
            name='geoprovinceval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geoprovinceval_occurrence', to='gp.geologicalprovince'),
        ),
        migrations.AddField(
            model_name='occurrencechange',
            name='sizeval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sizeval_occurrence', to='gp.occsize'),
        ),
    ]
