# Generated by Django 3.1.7 on 2021-05-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0024_auto_20210511_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occname',
            name='name',
            field=models.CharField(max_length=130, unique=True),
        ),
    ]
