# Generated by Django 3.1.7 on 2021-05-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0025_auto_20210517_1224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together=set(),
        ),
    ]
