# Generated by Django 3.1.7 on 2021-05-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0026_auto_20210518_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrencechange',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tenementchange',
            name='id',
        ),
        migrations.AddField(
            model_name='occurrencechange',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenementchange',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='listed',
            unique_together=set(),
        ),
    ]
