# Generated by Django 3.1.7 on 2021-05-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0027_auto_20210520_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrencechange',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='tenementchange',
            old_name='date',
            new_name='date_created',
        ),
    ]
