# Generated by Django 3.1.7 on 2021-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0029_auto_20210520_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolderChange',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=6)),
                ('field', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('date_created', models.DateField()),
                ('childval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childval_holder', to='gp.holder')),
                ('ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_change', to='gp.holder')),
                ('listedval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listedval_holder', to='gp.listed')),
                ('parentval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parentval_holder', to='gp.holder')),
            ],
        ),
    ]
