# Generated by Django 3.1.7 on 2021-05-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0030_holderchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenementchange',
            name='geoprovinceval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geoprovinceval_tenement', to='gp.geologicalprovince'),
        ),
    ]
