# Generated by Django 3.1.7 on 2021-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0031_tenementchange_geoprovinceval'),
    ]

    operations = [
        migrations.AddField(
            model_name='holderchange',
            name='childperc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='holderchange',
            name='parentperc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
