# Generated by Django 3.1.7 on 2021-05-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0033_tenementchange_holderperc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenementchange',
            name='majmatval',
        ),
        migrations.RemoveField(
            model_name='tenementchange',
            name='minmatval',
        ),
    ]
