export const PRIMARY_GROUP_OPEN = 'PRIMARY_GROUP_OPEN'
export const PRIMARY_GROUP_CLOSE = 'PRIMARY_GROUP_CLOSE'
export const SECONDARY_GROUP_OPEN = 'SECONDARY_GROUP_OPEN'
export const SECONDARY_GROUP_CLOSE = 'SECONDARY_GROUP_CLOSE'
export const RESET_FILTER_GROUP = 'RESET_FILTER_GROUP'
export const CLOSE_ALL_GROUPS = 'CLOSE_ALL_GROUPS'

